export GITHUB_OWNER="17sushmita"
export GITHUB_REPO="hello-world"
export GITHUB_COMMENT_TYPE="pr"
export GITHUB_PR_ISSUE_NUMBER=1
export GITHUB_COMMENT_FORMAT="This is a sample comment generated by orb:<br/>{{.}}"
export GITHUB_COMMENT="Build Succeeded!!"

./src/scripts/comment.sh